### ISSUE TITLE
添加选择不同版本 Mesa 驱动的功能

### ISSUE THREAD

**Issue by Nekongawi** [HopiHopy/PojavZenithHorizon#40]
### 问题描述

請開發者更新下一個驅動，改成23.0.0 devel，有手機規格就好 真我C3/32 馬裡G57 我不支援在驅動程式 24.0.7 上玩 Zink 我支援驅動程式版本 24.0.4 及以下版本，這是最好的 Mesa 23.0.0 驅動程式是開發版，因為它很穩定且符合我的規格。因為我和我的朋友在舊的 Android 手機上經歷了同樣的事情

### 日志/截图或视频

[crash-2024-05-24_21.33.27-client.txt](https://github.com/HopiHopy/PojavZH/files/15436497/crash-2024-05-24_21.33.27-client.txt)

### 复现步骤

```markdown
閱讀上面的內容
```

### 预期行为

我希望有一個像 Pojav Glow worm 這樣的功能，對於鋅渲染用戶來說是一個很好的功能，即 Select Driver，它由以下部分組成 Mesa 22.0.5/Mesa 23.0.0 devel/Mesa24.0.4/Mesa 24++ 等等我希望這樣我的舊手機可以使用Zink Render

### 其他信息

```markdown
- 设备型号：Realme c31
- CPU 架构：(忘記）但是Mali g57 GPU
- Android 版本：11
- PojavZH 版本：1.1.0
```

**Comment by Vera-Firefly** [comment]
> 那麼什麼時候會加入Extra Mesa呢？

静静等待吧,短期内不会改变

**Comment by Vera-Firefly** [comment]
https://github.com/HopiHopy/PojavZenithHorizon/pull/54
