### ISSUE TITLE
[BUG] чёрные текстуры блоков | virglrenderer

### ISSUE THREAD

**Issue by TopedGames** [HopiHopy/PojavZenithHorizon#49]
### 问题描述

Установлено: version — 1.20.6 OptiFine, java — 21, визуализатор — virglrenderer, OpenGL — 4.6, Mesa — 22.0.5, без шейдеров.
Просто чёрные текстуры блоков и их анимаций.

### 日志/截图或视频

![Screenshot_2024-06-20-12-03-40-88_157888a6fcdf6147cb3f40e862978649](https://github.com/HopiHopy/PojavZH/assets/150599356/e4176d3e-64f7-4908-af8f-97d7e87a7a90)
![Screenshot_2024-06-20-12-03-17-72_157888a6fcdf6147cb3f40e862978649](https://github.com/HopiHopy/PojavZH/assets/150599356/c89237b2-01d3-4c83-92f3-da5db44f454b)
![Screenshot_2024-06-20-12-02-20-65_157888a6fcdf6147cb3f40e862978649](https://github.com/HopiHopy/PojavZH/assets/150599356/68a4c4b3-4c15-4d14-8aa2-c23b327a01a8)
![Screenshot_2024-06-20-12-01-51-14_157888a6fcdf6147cb3f40e862978649](https://github.com/HopiHopy/PojavZH/assets/150599356/c67ccf15-1923-4cc4-9ee5-0fedc71848c8)

### 复现步骤

```markdown
1. Запуск лаунчера.
2. Захожу на карту.
3. Баг текстур.
```

### 预期行为

Игра стабильна.

### 其他信息

```markdown
- 设备型号：realme C2
- CPU 架构：arm64-v8a
- Android 版本：9
- PojavZH 版本：1.1.2
```

**Comment by Vera-Firefly** [comment]
This problem comes from vtest, and we have no way to fix it
