### ISSUE TITLE
启用Zink渲染器导致崩溃

### ISSUE THREAD

**Issue by HuiYuanXin13** [HopiHopy/PojavZenithHorizon#52]
### 问题描述

本来我想为 MC1.20.1-optifine 加个光影

但是在默认渲染器中gl4es下会发生渲染错误，导致出现关闭平滑光照的效果

想起PojavLauncher（适用于 Android 的《Minecraft：Java版》），版本edelweiss-20240122-693f90b-v3_openjdk，在gl4es下有同样的错误，而在Zink下正常

于是使用Zink，但是无法进入游戏界面

试了1.7.10（默认），1.20.1（原版）都如此

### 日志/截图或视频

[latestlog.txt](https://github.com/user-attachments/files/15964340/latestlog.txt)

### 复现步骤

```markdown
1. 打开启动器
2. 打开右上角的设置
3. 视频设置-渲染器，选择Zink
```

### 预期行为

我想就算Zink下无法使用使用光影，也至少应该可以进入游戏

### Android 版本

13

### Pojav Zenith Horizon 版本

1.2.3

### 其他信息

```markdown
手机：Redmi Note 12 Turbo (16GB + 1TB)
系统：MIUI 14.0.27
架构：arm-v8a
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
孩子,你貌似中奖了,概率极小的GLSL问题被你给遇上了

**Comment by Vera-Firefly** [comment]
尝试使用渲染器实验性设置中的自定义GL/GLSL
或者使用Mesa23.0.4的zink
这个提议可以关闭了
