### ISSUE TITLE
图标显示不全

### ISSUE THREAD

**Issue by MCmuqi** [HopiHopy/PojavZenithHorizon#64]
### 问题描述

当在编辑实例界面中修改图标时 上传一个1:1的图像后 显示的图标将会变成一个长条形 并且经过我的测试 1080*1081的图像却不会产生此bug
![1719971496474](https://github.com/HopiHopy/PojavZenithHorizon/assets/139481824/783ed6f9-ed8d-4691-a3b2-09e951ca48c2)

### 日志/截图或视频

https://github.com/HopiHopy/PojavZenithHorizon/assets/139481824/40a38436-a5ba-42ae-9791-9c73cfdac8f3

### 复现步骤

```markdown
1.打开启动器
2.展开实例
3.选择一个实例
4.编辑实例
5.编辑实例图标
6.选择一个比例1:1的图像
7.图像变为长条
```

### 预期行为

无法对图像进行更好地编辑，影响体验

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.4

### 其他信息

```markdown
- 设备型号：
iQOO Z8
- CPU 架构：
4 x ARM Cortex-A78
4 x ARM Cortex-A55
- GPU 信息：
渲染器 Mali-G610 MC6
版本 OpenGL ES 3.2 v1.r38p1
```

### 这个问题还没有人反馈过

- [x] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by gumen2258** [comment]
我刚刚试了一下，根本看不见图标😭

**Comment by gumen2258** [comment]
https://github.com/HopiHopy/PojavZenithHorizon/assets/136236969/6a6e626c-b3fe-4e29-ba8a-dd5f6980c79e

**Comment by MCmuqi** [comment]
> 我刚刚试了一下，根本看不见图标😭

它的图标应该是只显示左边一部分 你的左边是透明的 所以看不见❤️

**Comment by gumen2258** [comment]
> > 我刚刚试了一下，根本看不见图标😭
> 
> 它的图标应该是只显示左边一部分 你的左边是透明的 所以看不见❤️

哦哦哦

**Comment by HopiHopy** [comment]
@MCmuqi 这个问题在官方原版就存在了，竖屏下怎么操作都是正常的，横屏模式下不对图标进行缩放就没有问题，如果横屏模式在编辑图标的时候放大（仅限放大）了图标，那么就会裁剪异常，请前往官方库反馈这个问题：
https://github.com/PojavLauncherTeam/PojavLauncher/issues/new/choose

**Comment by MCmuqi** [comment]
> @MCmuqi 这个问题在官方原版就存在了，竖屏下怎么操作都是正常的，横屏模式下不对图标进行缩放就没有问题，如果横屏模式在编辑图标的时候放大（仅限放大）了图标，那么就会裁剪异常，请前往官方库反馈这个问题： https://github.com/PojavLauncherTeam/PojavLauncher/issues/new/choose

我在这几次编辑中都没有进行缩放 还是有这样的问题

**Comment by HopiHopy** [comment]
> 我在这几次编辑中都没有进行缩放 还是有这样的问题
@MCmuqi 但它已经被证实为PojavLauncher官方的问题，我们没有能力亲自修复这个问题，请前往官方库反馈：
https://github.com/PojavLauncherTeam/PojavLauncher/issues/new/choose
