### ISSUE TITLE
光标样式修改

### ISSUE THREAD

**Issue by CloudBack0601** [HopiHopy/PojavZenithHorizon#66]
### 功能描述

加入可选择系统插入外设时的自带鼠标光标和windows光标的切换选项

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by HopiHopy** [comment]
@CloudBack0601 不能，这是属于系统级修改，我们没有计划也没有能力这么做
