### ISSUE TITLE
内存分配添加输入选项

### ISSUE THREAD

**Issue by lselisi** [HopiHopy/PojavZenithHorizon#69]
### 功能描述

能不能给内存分配那个位置添加一个输入或者微调的选择，而非只有稍稍一动就是几百兆变化的滑块

### 这个功能建议还没有人提出过

- [X] 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出

**Comment by gumen2258** [comment]
这个不是早就有了吗？

**Comment by gumen2258** [comment]
点内存分配条上面的文字就可以了

**Comment by gumen2258** [comment]
https://github.com/HopiHopy/PojavZenithHorizon/assets/136236969/18d91897-9c86-4918-a88a-17737a99002e

**Comment by lselisi** [comment]
> SVID_20240704_185155_1.mp4

嗷嗷，抱歉抱歉，咱以为那个不能点的
