### ISSUE TITLE
[BUG] 1.12.2forge版本加mod后进游戏黑屏

### ISSUE THREAD

**Issue by desdd2** [HopiHopy/PojavZenithHorizon#73]
### 问题描述

1.12.2forge版本加mod后进游戏黑屏但游戏正常运行

### 日志/截图或视频

https://github.com/HopiHopy/PojavZenithHorizon/assets/174854001/22ded445-690d-4ad2-b977-e81d553c10f7

### 复现步骤

```markdown
1.打开启动器
2.安装1.12.2forge版本
3.添加mod
4.进入游戏
```

### 预期行为

游戏正常运行仅仅是黑屏

### Android 版本

14

### Pojav Zenith Horizon 版本

1.2.4.1

### 其他信息

```markdown
- 设备型号：huawei nova10 pro
- CPU 架构：高通骁龙778G
- GPU 信息：
```

### 这个问题还没有人反馈过

- [X] 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by HopiHopy** [comment]
@desdd2 由于过长时间没有提供日志文件或更有用的信息，我决定关闭这个议题，如有异议，请提供日志文件，并重新打开这个议题。
